module.exports = {
   getModulesInfoMin:`api/ApiModules/getModulesInfoMin?moduleType=const`,
   getAllProjectInfo:`api/ApiConstruction/getAllProjectInfo?`,
   getAllProjectInfo_dyb:`api/ApiConstruction/getAllProjectInfo?`,
   getBuildNotes:`api/ApiConstruction/getBuildNotes?`,
   Task_category:`api/ApiTask/getTaskCategory?`,
   Task_List:`api/ApiTask/getTaskComboList?`,
   Task_priority:`api/ApiTask/getTaskPriority?`,
   Task_status:`api/ApiTask/getTaskStatusCombo?`,
   Task_Users:`api/ApiGetCommonInfo/getUsers?`,
   Task_Project:`api/ApiTask/getCategoryRelatedTableComboList?`,
   getCountry:`api/ApiGetCommonInfo/getCountry`,
   getCity:`api/ApiGetCommonInfo/getCity`,
   CreatProject:`api/ApiConstruction/addProject`,
   UpdateProject:`api/ApiConstruction/updateProject`,
   CreateSite:`api/ApiConstruction/addSite`,
   UpdateSite:`api/ApiConstruction/updateSite`,
   DeleteBuildNote:`api/ApiConstruction/deleteBuildNote`,
   AddBuildNotes:`api/ApiConstruction/addBuildNotes`,
   AddTask:`api/ApiTask/createTask`,
   DeleteUnit:`api/ApiConstruction/deleteUnit`,
   CreateUnit:`api/ApiConstruction/addUnit`,
   UpdateUnit:`api/ApiConstruction/updateUnit`,
   UpdateSection:`api/ApiConstruction/updateSection`,
   CreateSection:`api/ApiConstruction/addSection`,
   DeleteSection:`api/ApiConstruction/deleteSection`,
   UpdateFeature:`api/ApiConstruction/updateFeature`,
   DeleteFeature:`api/ApiConstruction/deleteFeature`,
   CreateFeature:`api/ApiConstruction/addFeature`,
   UpdateBuildNote:`api/ApiConstruction/updateBuildNote`,
   gtCountry:`api/ApiGetCommonInfo/getCountry`

}

