const LATITUDE = 35.6892;
const LONGITUDE = 51.389;
module.exports = {
  BASE_URL_User: "",
  BASE_URL_first: 'https://master.okout.net/api/ApiLogin/checkOrgCode',
  FONT_FAMILY: "yekanbakh",
  FONT_FAMILY1: "IRANSansMobileFaNum-Medium",
  FONT_FAMILYHEAVY: "YEKANBAKHEN07HEAVY",
  FONT_FAMILY_BOLD: "YekanBakhBold",
  FONT_FAMILY_ENGLISH: "yekanbakh",
  OFFICIAL_GREEN_COLOR: "#bded80",
  OFFICIAL_ORANGE_COLOR: "#ecd897",
  OFFICIAL_WITE_COLOR: "#fff",
  OFFICIAL_BLUE_COLOR: "#C7D9F3B2",
  OFFICIAL_PURPLE_COLOR: "#999999",
  OFFICIAL_background: "#181b2c",
  OFFICIAL_Button: "#5658DD",
  OFFICIAL_Buttondark: "#2122b6",
  OFFICIAL_backgroundItem: "#2A3052FF",
  OFFICIAL_backgroundItem_Light: "rgba(42,48,82,0.6)",
  OFFICIAL_backgroundItem_Lighter: "#434a79",
  OFFICIAL_PROJECTCOLOR:"#FF0000",
  REGION: {
    latitude: LATITUDE,
    longitude: LONGITUDE,
    latitudeDelta: 0.03,
    longitudeDelta: 0.03,
  },
  token: "",
  PASSWORD_KEY: "@MySuperStore:password",
  OrgAppLink: "@MySuperStore:OrgAppLink",
  OrgAppKey: "@MySuperStore:OrgAppKey",
  VersionCheck: "@MySuperStore:VersionCheck",
  RoleID_Key: "@MySuperStore:RoleID",
  UserInfo: "@MySuperStore:UserInfo",
  Modules: "@MySuperStore:Modules",
  DYBList: "@MySuperStore:DYBList",
  SiteDetail_KEY: "@MySuperStore:SiteDetail_KEY",
  UnitDetail_KEY: "@MySuperStore:UnitDetail_KEY",
  SectionDetail_KEY: "@MySuperStore:SectionDetail_KEY",
  FeatureDetailList_KEY: "@MySuperStore:FeatureDetailList_KEY",
  FeatureList_KEY: "@MySuperStore:FeatureDetailList_KEY",
  FeatureList_Details_KEY: "@MySuperStore:FeatureList_Details_KEY",
  DYBList_Details_KEY: "@MySuperStore:DYBList_Details_KEY",
  DYBlList_KEY: "@MySuperStore:DYBlList_KEY",
  Methdos_KEY: "@MySuperStore:Methdos_KEY",
  DYBProjectsDetails: "@MySuperStore:DYBProjectsDetails",
  FeatureAdd_Image_KEY: "@MySuperStore:FeatureAdd_Image_KEY",
  offline_data: "@MySuperStore:offline_data",
  All_Lists:'@MySuperStore:All_Lists',
  All_Country:'@MySuperStore:All_Country',
  All_City:'@MySuperStore:All_City',
  AllProjectInfo_dyb:'@MySuperStore:AllProjectInfo_dyb',
  All_Task:'@MySuperStore:All_Task',
  PASSWORD_value:"",
  OrgAppLink_value:"",
  OrgAppKey_value:"",
  modules:[],
  ProjectId:0,
  SiteId:0,
  UnitId:0,
  SectionId:0,
  SectionIdDelete:0,
  FeatureIdDelete:0,
  UpdateProjectId:0,
  UnitIdDelete:0,
  UpdateSiteID:0,
  UpdateUnitID:0,
  UpdateSectionID:0,
  UpdateFeatureID:0,
  DYB:'',
  SectionName:'',
  MenuName:'',
  FeatureName:'',
  FeatureNameDetail:'',
  FeatureSelectDetail:'',
  Feature:"",
  RoleID:0,
  UserInformation:'',
  isConnected:true,
  SiteDetailList:[],
  UpdateId:0,
  location:'',
  DYB_Type:'',
  buildId:0,
  Navigation:'',
  Country:[],
  City:[],
  AllProjectInfo:[],

};
